"""BTagent shared types — re-export commonly used models."""

from btagent_shared.types.config import (
    TLP,
    AgentConfig,
    AutonomyLevel,
    IntegrationAutonomy,
    MCPConnection,
    ModelProvider,
    ModelTier,
)
from btagent_shared.types.enums import (
    AuditCategory,
    AuditOutcome,
    ContainmentStatus,
    InvestigationStatus,
    IOCType,
    Severity,
    UserRole,
)
from btagent_shared.types.events import EventEnvelope, EventType
from btagent_shared.types.investigation import (
    IOC,
    ContainmentAction,
    Evidence,
    Investigation,
    TimelineEntry,
)
from btagent_shared.types.knowledge import (
    IngestRequest,
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeSourceType,
    QueryRequest,
    QueryResponse,
    SearchResult,
)
from btagent_shared.types.playbook import (
    ActionStep,
    DecisionStep,
    HITLGateStep,
    OnFailure,
    ParallelForkStep,
    PlaybookDefinition,
    PlaybookExecution,
    PlaybookStatus,
    PlaybookStep,
    StepResult,
    StepType,
    TriggerCondition,
    TriggerType,
    ValidationResult,
)
from btagent_shared.types.workflow import (
    CreateWorkflowRequest,
    CreateWorkflowVersionRequest,
    UpdateWorkflowRequest,
    UpdateWorkflowVersionRequest,
    WorkflowListResponse,
    WorkflowResponse,
    WorkflowVersionListResponse,
    WorkflowVersionResponse,
    WorkflowVersionState,
)
from btagent_shared.types.hunt import (
    Backend,
    CorrelationRule,
    ExecSummary,
    Finding,
    HuntInput,
    HuntPlan,
    HuntPlanState,
    HuntScope,
    Hypothesis,
    NoiseProfile,
    PostHuntAction,
    Query,
    TTPRunbookEntry,
    TTPState,
)
from btagent_shared.types.connector import (
    ActionCapability,
    BlastRadius,
    ConnectorManifest,
    CostClass,
    CredentialType,
    OCSFEventClass,
    QueryCapability,
    StreamCapability,
    TransportKind,
)
from btagent_shared.types.correlation import (
    AuditEntry,
    CorrelationTimeline,
    MitreTag,
    NormalizedEvent,
    PivotSuggestion,
    RawEventRef,
)
from btagent_shared.types.query_ir import (
    LogicOp,
    Operator,
    QueryCondition,
    QueryIR,
)

__all__ = [
    "AgentConfig",
    "AuditCategory",
    "AuditOutcome",
    "AutonomyLevel",
    "ContainmentAction",
    "ContainmentStatus",
    "EventEnvelope",
    "EventType",
    "Evidence",
    "IOC",
    "IOCType",
    "IngestRequest",
    "IntegrationAutonomy",
    "Investigation",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "KnowledgeSourceType",
    "InvestigationStatus",
    "MCPConnection",
    "ModelProvider",
    "ModelTier",
    "QueryRequest",
    "QueryResponse",
    "SearchResult",
    "Severity",
    "TLP",
    "TimelineEntry",
    "UserRole",
    # Playbook types
    "ActionStep",
    "DecisionStep",
    "HITLGateStep",
    "OnFailure",
    "ParallelForkStep",
    "PlaybookDefinition",
    "PlaybookExecution",
    "PlaybookStatus",
    "PlaybookStep",
    "StepResult",
    "StepType",
    "TriggerCondition",
    "TriggerType",
    "ValidationResult",
    # Workflow CRUD types (Phase 2 v1)
    "CreateWorkflowRequest",
    "CreateWorkflowVersionRequest",
    "UpdateWorkflowRequest",
    "UpdateWorkflowVersionRequest",
    "WorkflowListResponse",
    "WorkflowResponse",
    "WorkflowVersionListResponse",
    "WorkflowVersionResponse",
    "WorkflowVersionState",
    # Hunt types (Phase A of #99)
    "Backend",
    "CorrelationRule",
    "ExecSummary",
    "Finding",
    "HuntInput",
    "HuntPlan",
    "HuntPlanState",
    "HuntScope",
    "Hypothesis",
    "NoiseProfile",
    "PostHuntAction",
    "Query",
    "TTPRunbookEntry",
    "TTPState",
    # Connector manifest types (#100)
    "ActionCapability",
    "BlastRadius",
    "ConnectorManifest",
    "CostClass",
    "CredentialType",
    "OCSFEventClass",
    "QueryCapability",
    "StreamCapability",
    "TransportKind",
    # Correlation types (UC-1.2)
    "AuditEntry",
    "CorrelationTimeline",
    "MitreTag",
    "NormalizedEvent",
    "PivotSuggestion",
    "RawEventRef",
    # Query IR (UC-1.3)
    "LogicOp",
    "Operator",
    "QueryCondition",
    "QueryIR",
]
